### ISSUE TITLE
As a SO, I would like to maintain a list a acronyms

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/directory#19]
@kreynen commented on [Tue Oct 31 2017](https://github.com/CuBoulder/express/issues/1652)

## Context

When I went to the Hacky Hours, the grad student tried to look up the acronym for the org unit I worked for using https://www.colorado.edu/bfa/resources/acronyms.  None of the potential acronyms for the unit I work for existed in that list.  Not only is that far from accurate, it is being maintained as a basic page.  A search for acronyms shows that this is a fairly common content type on Express sites.

https://www.colorado.edu/geography/gcraft/notes/gps/acronym.html
https://www.colorado.edu/ecenter/recycling/resources/curricular-resources/recycling-glossary-and-acronyms
https://www.colorado.edu/researchinnovation/sites/default/files/attached-files/abbreviations_and_acronyms.pdf
https://www.colorado.edu/engineering/civil/CVEN4474/resources/RemedAcron.pdf
https://www.colorado.edu/ecenter/sites/default/files/attached-files/recycling_acronyms.pdf

I think we should create an Acronym Bundle as well as maintaining an official acronym list as part of https://www.colorado.edu/strategicrelations/services/print/writingediting/style-guide/abbreviations

---

@kevincrafts commented on [Tue Oct 31 2017](https://github.com/CuBoulder/express/issues/1652#issuecomment-340809837)

Talked with Paul & Kristin and they both agree that this should go within the brand site where we already have a word list: https://www.colorado.edu/brand/how-use/text-tone/cu-boulder-word-list and direction on abbreviation use https://www.colorado.edu/brand/how-use/text-tone/editorial-style-guide/abbreviations

**Comment by alexfinnarn** [comment]
Well, this issue looks like it will be a list of text manually maintained in an Express site?
