### ISSUE TITLE
List of Current Endpoints

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/directory#3]
@alexfinnarn commented on [Fri Jul 27 2018](https://github.com/CuBoulder/express/issues/2818)

The homepage bundle provides some paths accessed in the directory API, but there might be other ones...probably not listed anywhere.

- **/letter/%** - Gives a listing based on letter
- **/show/%** - Shows a particular ID of a directory record...doesn't work...only in Drupal module menu paths
- **/category/%** - List of categories
- **/ou/%** 

http://atozapi.colorado.edu/letter/b

http://atozapi.colorado.edu/categories
http://atozapi.colorado.edu/category/museum

**Comment by alexfinnarn** [comment]
I'm pretty sure this issue is useless now. It is my understanding that the entire directory will be replaced with new data so the current data structure and endpoints don't matter.
