### ISSUE TITLE
Scope A to Z Replacement

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/directory#5]
@alexfinnarn commented on [Thu Jul 26 2018](https://github.com/CuBoulder/express/issues/2816)

The directory http://atozapi.colorado.edu/ needs to be replaced with something. Since our team knows PHP, it makes sense to create the stack around PHP and explore Laravel in the process. One could also start with basic Symfony components (Laravel uses some Symfony components).

I know that the homepage bundle connects to the directory to look up people
https://www.colorado.edu/atoz/letter/a
https://github.com/CuBoulder/custom_homepage_bundle/tree/master/modules/custom/cu_atoz

I don't know much about the current issues already out there in the Express repo, but the first step would be to capture what the Directory API does and how it interacts with its consumers. I think the Homepage is the only consumer, but I'm not sure.

Also involved here is getting "expert" advice from Symfony/API Platform/Laravel community and any local/remote shops that could do contract work and/or consultations.

**Comment by alexfinnarn** [comment]
I have a list of docs and spreadsheet for my current understanding of scope.

- Directory scope document
- Organization spreadsheet 
- Organization structure document

I didn't put the URLs since I'm not certain how those are shared. I will keep those links and can share if people want them.
